# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20170919_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
